window.CONTRACT_APP_REPORTS = (() => {
  const reportDefinitions = [
    { id: "custom-builder", name: "Custom Report Builder", group: "Custom", description: "Pick date range, facility, vendor, service/category, source, status, and columns." },
    { id: "contract-inventory", name: "Contract Inventory", group: "Core", description: "All contracts with facility, vendor, category, status, risk, spend, and PDF status." },
    { id: "current-contracts", name: "Current Contract View", group: "Core", description: "One best current record per vendor, facility, and service, with history count." },
    { id: "approved-contracts", name: "Approved Contracts", group: "Core", description: "Contracts approved after OCR review." },
    { id: "needs-review", name: "Needs Review Queue", group: "Core", description: "Contracts still needing human approval or field cleanup." },
    { id: "contract-history", name: "Contract History / Archived", group: "Core", description: "Archived or old contracts kept for history." },
    { id: "expiring-30", name: "Expiring in 30 Days", group: "Renewals", description: "Urgent renewals and expirations due in the next 30 days." },
    { id: "expiring-90", name: "Expiring in 90 Days", group: "Renewals", description: "Contracts expiring soon enough for negotiation planning." },
    { id: "expiring-180", name: "Expiring in 180 Days", group: "Renewals", description: "Longer-range renewal calendar." },
    { id: "auto-renewal", name: "Auto-Renewal Contracts", group: "Renewals", description: "Contracts where auto-renewal is confirmed." },
    { id: "auto-renewal-action", name: "Auto-Renewal Action", group: "Renewals", description: "Auto-renewal contracts with notice deadline, days left, and required action." },
    { id: "unknown-renewal-status", name: "Unknown Renewal Status", group: "Renewals", description: "Contracts where auto-renewal still needs review." },
    { id: "termination-missing", name: "Termination Notice Missing", group: "Renewals", description: "Records where exit notice is unknown or missing." },
    { id: "high-risk", name: "High-Risk Contracts", group: "Risk", description: "Risk-ranked contracts that need legal or operations attention." },
    { id: "missing-insurance", name: "Missing Insurance / Compliance", group: "Risk", description: "Contracts or vendors missing insurance and compliance proof." },
    { id: "signer-missing", name: "Signer Missing", group: "Risk", description: "Contracts where the signer or title was not extracted." },
    { id: "signed-date-missing", name: "Signed Date Missing", group: "Risk", description: "Contracts where the executed date is missing." },
    { id: "missing-pdf", name: "Source PDF Missing", group: "Risk", description: "Records without a local source PDF link." },
    { id: "data-quality", name: "Contract Data Quality", group: "Risk", description: "Missing facility, vendor, category, dates, spend, signer, and account fields." },
    { id: "vendor-directory", name: "Vendor Directory", group: "Vendors", description: "Vendor profile export with address, phone, email, spend, and issues." },
    { id: "vendor-address-gaps", name: "Vendor Mailing Address Gaps", group: "Vendors", description: "Vendors that still need a real mailing address." },
    { id: "vendor-account-ids", name: "Vendor Account IDs", group: "Vendors", description: "Account, customer, member, policy, site, location, or utility numbers found." },
    { id: "spend-by-vendor", name: "Spend by Vendor", group: "Finance", description: "Annual spend summarized by vendor." },
    { id: "spend-by-facility", name: "Spend by Facility", group: "Finance", description: "Annual spend summarized by facility." },
    { id: "spend-by-category", name: "Spend by Category", group: "Finance", description: "Annual spend summarized by contract category." },
    { id: "spend-by-service-vendor", name: "Spend by Service and Vendor", group: "Finance", description: "Total annualized spend for each service/category and vendor, such as all snow plow vendors." },
    { id: "price-change-tracker", name: "Price Change Tracker", group: "Finance", description: "Compare older and newer contracts by service/vendor/facility to spot increases, decreases, and renegotiation targets." },
    { id: "service-rate-benchmark", name: "Service Rate Benchmark", group: "Finance", description: "Compare fee lines and rates by service, unit, vendor, and facility." },
    { id: "possible-overpay", name: "Possible Overpay Flags", group: "Finance", description: "Contracts above similar service/category cost-per-bed or annual spend averages." },
    { id: "contract-approval-justifications", name: "Approval Justifications", group: "Finance", description: "Why a contract was approved when pricing is higher, lower, or unusual compared with similar contracts." },
    { id: "per-bed-ppd-finance", name: "Per Bed / PPD Finance", group: "Finance", description: "Annualized spend, monthly run rate, cost per bed/month, and estimated PPD by contract." },
    { id: "rate-fee-lines", name: "Rate / Fee Lines", group: "Finance", description: "Extracted rates, fees, units, escalation, and source proof." },
    { id: "unit-day-rates", name: "Unit / Per-Day Rates", group: "Finance", description: "Per-unit, per-day, per-bed, per-service, or other contract pricing." },
    { id: "payment-terms", name: "Payment Terms", group: "Finance", description: "Payment terms found in approved contracts and vendor profiles." },
    { id: "facility-coverage", name: "Facility Coverage", group: "Facilities", description: "Facility profile, contract count, spend, missing categories, and weather coordinates." },
    { id: "category-coverage", name: "Category Coverage", group: "Facilities", description: "Contract count and coverage by category." },
    { id: "utility-accounts", name: "Utility / Account Numbers", group: "Facilities", description: "Facility/vendor accounts, meters, service addresses, and source." },
    { id: "service-addresses", name: "Service Addresses", group: "Facilities", description: "Service location addresses extracted from contracts or imported account files." },
    { id: "ocr-jobs", name: "OCR Jobs", group: "OCR", description: "Every upload/read job and whether text extraction completed." },
    { id: "ocr-failed", name: "OCR Failed Jobs", group: "OCR", description: "OCR jobs that failed or still need attention." },
    { id: "low-confidence", name: "Low Confidence Fields", group: "OCR", description: "Extracted fields likely needing review before approval." },
    { id: "needs-correction", name: "Needs Correction", group: "OCR", description: "Contracts with missing key fields, low confidence, duplicates, or renewal/notice risks." },
    { id: "invoice-matches", name: "Invoice Match Checks", group: "Invoices", description: "Temporary invoice checks and matched contract confidence." },
    { id: "weather-history", name: "Weather Check History", group: "Invoices", description: "Historical snow and precipitation checks used for invoice review." },
    { id: "invoice-needs-match", name: "Invoices Needing Match", group: "Invoices", description: "Invoice checks that did not confidently match to a contract." },
    { id: "weather-snow-events", name: "Snow Event Charges", group: "Invoices", description: "Weather checks where snow was found for invoice review." },
    { id: "contract-type-summary", name: "Contract Type Summary", group: "Operations", description: "Contract count by agreement type or extracted document type." },
    { id: "facility-vendor-matrix", name: "Facility Vendor Matrix", group: "Operations", description: "Which vendors serve which facilities." },
    { id: "facility-category-matrix", name: "Facility Category Matrix", group: "Operations", description: "Which contract categories exist at each facility." },
    { id: "vendor-facility-count", name: "Vendor Facility Count", group: "Operations", description: "Vendors ranked by number of facilities served." },
    { id: "unknown-vendors", name: "Unknown Vendors", group: "Operations", description: "Contracts where the vendor still needs classification." },
    { id: "unknown-facilities", name: "Unknown Facilities", group: "Operations", description: "Contracts where the facility still needs classification." },
    { id: "unknown-categories", name: "Unknown Categories", group: "Operations", description: "Contracts where the category still needs classification." },
    { id: "large-spend-contracts", name: "Large Spend Contracts", group: "Finance", description: "Highest spend contracts loaded in the system." },
    { id: "missing-spend", name: "Missing Spend", group: "Finance", description: "Contracts that need cost, rate, or annual spend entered." },
    { id: "monthly-run-rate", name: "Monthly Run Rate", group: "Finance", description: "Estimated monthly value from indexed annual spend." },
    { id: "fee-lines-missing", name: "Missing Fee Schedule", group: "Finance", description: "Contracts without extracted fee or rate lines." },
    { id: "vendor-contact-gaps", name: "Vendor Contact Gaps", group: "Vendors", description: "Vendors missing phone or email." },
    { id: "vendor-insurance-gaps", name: "Vendor Insurance Gaps", group: "Vendors", description: "Vendors with missing or unclear insurance status." },
    { id: "vendor-payment-terms-gaps", name: "Vendor Payment Terms Gaps", group: "Vendors", description: "Vendors missing payment terms." },
    { id: "account-number-gaps", name: "Account Number Gaps", group: "Vendors", description: "Contracts missing account, customer, member, policy, site, or utility numbers." },
    { id: "service-address-gaps", name: "Service Address Gaps", group: "Facilities", description: "Contracts missing service location address." },
    { id: "facility-weather-coordinates", name: "Facility Weather Coordinates", group: "Facilities", description: "Facilities with latitude and longitude saved for real weather lookup." },
    { id: "missing-weather-coordinates", name: "Missing Weather Coordinates", group: "Facilities", description: "Facilities that still need coordinates before snow reports work." },
    { id: "ocr-complete", name: "OCR Completed", group: "OCR", description: "OCR jobs that completed and produced readable text." },
    { id: "ocr-queued", name: "OCR Waiting", group: "OCR", description: "OCR jobs still queued, running, or waiting to read." },
    { id: "contracts-with-ocr-text", name: "Contracts With OCR Text", group: "OCR", description: "Contracts where readable contract text is saved." },
    { id: "contracts-without-ocr-text", name: "Contracts Without OCR Text", group: "OCR", description: "Contracts missing readable OCR text." },
    { id: "renewal-owner", name: "Renewal Owner Report", group: "Renewals", description: "Contracts by owner and renewal responsibility." },
    { id: "expired-contracts", name: "Expired Contracts", group: "Renewals", description: "Contracts with an end date already passed." },
    { id: "no-end-date", name: "No Fixed End Date", group: "Renewals", description: "Contracts where no explicit expiration/end date was found. This is normal for many service agreements; review term, renewal, and termination instead." },
    { id: "notice-90-plus", name: "90+ Day Notice", group: "Renewals", description: "Contracts that mention 90 or 120 day notice requirements." },
    { id: "insurance-clause-check", name: "Insurance Clause Check", group: "Legal", description: "Insurance language found or missing by contract." },
    { id: "hipaa-clause-check", name: "HIPAA Clause Check", group: "Legal", description: "Healthcare privacy language found or missing by contract." },
    { id: "indemnification-check", name: "Indemnification Check", group: "Legal", description: "Indemnification language found or missing by contract." },
    { id: "liability-check", name: "Liability Limitation Check", group: "Legal", description: "Limitation of liability language found or missing by contract." },
    { id: "audit-rights-check", name: "Audit Rights Check", group: "Legal", description: "Audit rights language found or missing by contract." },
    { id: "audit-trail", name: "Audit Trail", group: "Admin", description: "Who changed, approved, uploaded, deleted, or updated records." },
    { id: "admin-settings-summary", name: "Admin Settings Summary", group: "Admin", description: "Saved system settings, roles, categories, and facility profiles." }
  ];

  return { reportDefinitions };
})();
